on: [push]

jobs:
  deploy:
    uses: VICENTE0777/proveedor-ciclo.vida.sofware/.github/workflows/deploy-api.yaml@main

    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #test 3
